version: '3.5'

services:
        backend:
                image: backend
                environment:
                        - FRONT_URL=frontend:5000
                        - REDIS=redis
                        - DB_USERNAME=backend
                        - DB_PASSWORD=example
                        - DB_HOST=db
                depends_on:
                        - db
        frontend:
                image: frontend
                environment:
                        - API_URL=backend:8000
        redis:
                image: redis
        db:
                image: postgres
                restart: unless-stopped
                environment:
                        POSTGRES_PASSWORD: example
                        POSTGRES_USER: backend
        nginx:
                image: nginx
                volumes:
                        - ./nginx.conf:/etc/nginx/nginx.conf:ro
                ports:
                        - 80:80
