version: '3.5'

services:
        frontend:
                image: kurkkufront
                build: ml-kurkkumopo-frontend/.
                ports:
                        - 3000:3000
        backend:
                image: kurkkubackend
                build: ml-kurkkumopo-backend/.
                ports:
                        - 5000:5000
                volumes:
                        - model:/src/model/

        training:
                image: kurkkutraining
                build: ml-kurkkumopo-training/.
                volumes:
                        - model:/src/model/
                        - imgs:/src/imgs/
                        - data:/src/data/

volumes:
        model:
        imgs:
        data:

